apiVersion: v1
kind: Service
metadata:
  name: recommender-service
spec:
  selector:
    app: recommender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5555
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommender
  template:
    metadata:
      labels:
        app: recommender
    spec:
      containers:
        - name: recommender
          image: word_recommender:lates
          ports:
            - containerPort: 5555
