apiVersion: v1
kind: Service
metadata:
  name: recommender-service
spec:
  selector:
    app: recommender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5555
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recommender
  template:
    metadata:
      labels:
        app: recommender
    spec:
      containers:
        - name: recommender
          image: word-recommender:v1
          ports:
            - containerPort: 5555
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"

