MODEL_SAVE_PATH = "../pretrain/word_recommendation.h5"
DATA_FILE_PATH = "../data/data_19_9_2023.txt"
TOKENIZER_PATH = '../data/tokenizer.picker' 

OUTPUT_DIM = 128
DROPOUT_THRESHOLD = 0.5
LEARNING_RATE = 0.001
BATCH_SIZE = 128
EPOCHS = 1
NUM_NEXT_WORDS = 2
NUM_SAMPLES = 5
MAX_SEQ_LEN = 26

